// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdQht1sbypzdHhgG_1KjQnvNQ5vvOIB6g',
    appId: '1:394312833565:web:175f43734b546e4d01c4f4',
    messagingSenderId: '394312833565',
    projectId: 'appchitieu-nhom4',
    authDomain: 'appchitieu-nhom4.firebaseapp.com',
    storageBucket: 'appchitieu-nhom4.firebasestorage.app',
    measurementId: 'G-PPVTLV48LQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-6qhxYrjTF-5aJYfv95fSL2qlX_1nr4I',
    appId: '1:394312833565:android:5220f760dafabe2801c4f4',
    messagingSenderId: '394312833565',
    projectId: 'appchitieu-nhom4',
    storageBucket: 'appchitieu-nhom4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdQht1sbypzdHhgG_1KjQnvNQ5vvOIB6g',
    appId: '1:394312833565:web:54c4e588f967fce801c4f4',
    messagingSenderId: '394312833565',
    projectId: 'appchitieu-nhom4',
    authDomain: 'appchitieu-nhom4.firebaseapp.com',
    storageBucket: 'appchitieu-nhom4.firebasestorage.app',
    measurementId: 'G-BP29SS9L31',
  );
}
