// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTPColvnpuZMTdYKhzqc6KWczv16LqCWc',
    appId: '1:525491805249:web:0c7014eaba4ae2e8be3ac0',
    messagingSenderId: '525491805249',
    projectId: 'quanlichitieu-4470e',
    authDomain: 'quanlichitieu-4470e.firebaseapp.com',
    databaseURL: 'https://quanlichitieu-4470e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quanlichitieu-4470e.firebasestorage.app',
    measurementId: 'G-DK5YR7T2NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsDAeaBBX4asjWn0GGjgNELC6ZsqSd3yM',
    appId: '1:525491805249:android:aa154964f23324d8be3ac0',
    messagingSenderId: '525491805249',
    projectId: 'quanlichitieu-4470e',
    databaseURL: 'https://quanlichitieu-4470e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quanlichitieu-4470e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTPColvnpuZMTdYKhzqc6KWczv16LqCWc',
    appId: '1:525491805249:web:dbf90a2e0b676251be3ac0',
    messagingSenderId: '525491805249',
    projectId: 'quanlichitieu-4470e',
    authDomain: 'quanlichitieu-4470e.firebaseapp.com',
    databaseURL: 'https://quanlichitieu-4470e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quanlichitieu-4470e.firebasestorage.app',
    measurementId: 'G-DX8PKZLY3L',
  );

}