import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'app.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  // NOTE: Firebase requires firebase_options.dart which is generated by running:
  // flutterfire configure --project=<your-project-id>
  // 
  // For development without Firebase:
  // - The app will work but authentication and cloud features will not function
  // - You can test the UI and local features
  // 
  // To set up Firebase:
  // 1. Install Firebase CLI: npm install -g firebase-tools
  // 2. Login: firebase login
  // 3. Install FlutterFire CLI: dart pub global activate flutterfire_cli
  // 4. Configure: flutterfire configure --project=<your-project-id>
  // 5. This will create firebase_options.dart automatically
  
  try {
    await Firebase.initializeApp(
      // options: DefaultFirebaseOptions.currentPlatform,
    );
    debugPrint('✅ Firebase initialized successfully');
  } catch (e) {
    debugPrint('⚠️ Firebase initialization error: $e');
    debugPrint('ℹ️ App will continue without Firebase. Please run "flutterfire configure" to set up Firebase.');
  }

  runApp(const ProviderScope(child: SmartExpenseApp()));
}
